apiVersion: apps/v1
kind: Deployment

metadata:
  name: document-platform

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: document-platform

  template:

    metadata:
      labels:
        app: document-platform

    spec:

      containers:

      - name: document-platform

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

        env:

        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY

        envFrom:

        - configMapRef:
            name: document-platform-config

        - secretRef:
            name: document-platform-secret

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}

          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}

        readinessProbe:
          httpGet:
            path: /
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 5000

          initialDelaySeconds: 30
          periodSeconds: 20
