apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: document-platform-ingress

spec:

  ingressClassName: nginx

  rules:

  - host: document.local

    http:

      paths:

      - path: /

        pathType: Prefix

        backend:

          service:

            name: document-platform-service

            port:

              number: 80
